<?php
/**
 * File: cvjson.php
 * Description: Handles cvjson operations
 *
 * @package    StraboSpot Web Site
 * @author     Jason Ash <jasonash@ku.edu>
 * @copyright  2025 StraboSpot
 * @license    https://opensource.org/licenses/MIT MIT License
 * @link       https://strabospot.org
 */

$cvvals = new stdClass();

unset($cvarray);
$cvarray=array();

$cvarray['Spot:']='selectgroup';
$cvarray['Name']='spot_name';
$cvarray['Notes']='spot_notes';
$cvvals->spot = $cvarray;

unset($cvarray);
$cvarray=array();

$cvarray['3d Structures:']='selectgroup';
$cvarray['Approximate Scale (m)']='_3d_structures_approximate_scale_m_lobate';
$cvarray['Approximate Scale of Boudinage (m)']='_3d_structures_approximate_scale_of_boudinage';
$cvarray['Approximate Scale of Mullions (m)']='_3d_structures_approximate_scale_of_mullions';
$cvarray['Average Width of Boudin Neck (m)']='_3d_structures_average_width_of_boudin_neck';
$cvarray['Linear Measurement Quality']='_3d_structures_boudin_linear_measure_quality';
$cvarray['Plunge']='_3d_structures_boudinage_2nd_plunge';
$cvarray['Trend']='_3d_structures_boudinage_2nd_trend';
$cvarray['Uncertainty']='_3d_structures_boudinage_2nd_trend_uncertaint';
$cvarray['Competent Material']='_3d_structures_boudinage_competent';
$cvarray['Dip']='_3d_structures_boudinage_dip';
$cvarray['Dip Direction']='_3d_structures_boudinage_dip_direction';
$cvarray['Boudinage Geometry']='_3d_structures_boudinage_geometry';
$cvarray['Incompetent Material']='_3d_structures_boudinage_incompetent';
$cvarray['Plunge']='_3d_structures_boudinage_plunge';
$cvarray['Boudinage Shape']='_3d_structures_boudinage_shape';
$cvarray['Strike']='_3d_structures_boudinage_strike';
$cvarray['Trend']='_3d_structures_boudinage_trend';
$cvarray['Measured Uncertainty']='_3d_structures_boudinage_trend_uncertainty';
$cvarray['Wavelength (m)']='_3d_structures_boudinage_wavelength_m';
$cvarray['Boudinaged Layer Thickness (m)']='_3d_structures_boudinaged_layer_thickness_m';
$cvarray['Competent Material']='_3d_structures_competent_material_fold';
$cvarray['Ellipse Type']='_3d_structures_ellipse_type';
$cvarray['Orientation Uncertainty']='_3d_structures_ellipsoid_int_orient_uncertain';
$cvarray['Plunge']='_3d_structures_ellipsoid_int_plunge';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_int_plunge_uncertain';
$cvarray['Trend']='_3d_structures_ellipsoid_int_trend';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_int_trend_uncertaint';
$cvarray['Value']='_3d_structures_ellipsoid_int_value';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_int_value_uncertaint';
$cvarray['Orientation Uncertainty']='_3d_structures_ellipsoid_max_orient_uncertain';
$cvarray['Plunge']='_3d_structures_ellipsoid_max_plunge';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_max_plunge_uncertain';
$cvarray['Trend']='_3d_structures_ellipsoid_max_trend';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_max_trend_uncertaint';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_max_uncertainty';
$cvarray['Value']='_3d_structures_ellipsoid_max_value';
$cvarray['Orientation Uncertainty']='_3d_structures_ellipsoid_min_orient_uncertain';
$cvarray['Plunge']='_3d_structures_ellipsoid_min_plunge';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_min_plunge_uncertain';
$cvarray['Trend']='_3d_structures_ellipsoid_min_trend';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_min_trend_uncertaint';
$cvarray['Value']='_3d_structures_ellipsoid_min_value';
$cvarray['Uncertainty']='_3d_structures_ellipsoid_min_value_uncertaint';
$cvarray['Quality of Measurement']='_3d_structures_ellipsoid_quality';
$cvarray['Ellipsoid Type']='_3d_structures_ellipsoid_type';
$cvarray['Ellipsoidal Tensor Notes']='_3d_structures_ellipsoidal_tensor_notes';
$cvarray['Dip']='_3d_structures_elliptical_dip';
$cvarray['Dip Direction']='_3d_structures_elliptical_dip_direction';
$cvarray['Elliptical Data Notes']='_3d_structures_elliptical_notes';
$cvarray['Orientation Uncertainty']='_3d_structures_elliptical_orientation_uncerta';
$cvarray['Quality']='_3d_structures_elliptical_quality';
$cvarray['Quality of Measurement']='_3d_structures_elliptical_quality_of_measurem';
$cvarray['Rake']='_3d_structures_elliptical_rake';
$cvarray['Elliptical Ratio']='_3d_structures_elliptical_ratio';
$cvarray['Strike']='_3d_structures_elliptical_strike';
$cvarray['Value Uncertainty']='_3d_structures_elliptical_value_uncertainty';
$cvarray['Fabric Type']='_3d_structures_feature_type';
$cvarray['Dominant Fold Attitude']='_3d_structures_fold_attitude';
$cvarray['Dip']='_3d_structures_fold_fol_dip';
$cvarray['Dip Direction']='_3d_structures_fold_fol_dip_direction';
$cvarray['Orientation Quality']='_3d_structures_fold_fol_quality';
$cvarray['Strike']='_3d_structures_fold_fol_strike';
$cvarray['Foliation Type']='_3d_structures_fold_foliation_Type';
$cvarray['Description of Foliation']='_3d_structures_fold_foliation_description';
$cvarray['Fold Notes']='_3d_structures_fold_notes';
$cvarray['Dominant Fold Shape']='_3d_structures_fold_shape';
$cvarray['Plunge']='_3d_structures_fold_shortening_dir_plunge';
$cvarray['Trend']='_3d_structures_fold_shortening_dir_trend';
$cvarray['Uncertainty']='_3d_structures_fold_shortening_dir_uncertaint';
$cvarray['Folded Layer Thickness (m)']='_3d_structures_folded_layer_thickness_m';
$cvarray['Id']='_3d_structures_id';
$cvarray['Igneous/Migmatite Features Description']='_3d_structures_igneous_migmatite_feat_descrip';
$cvarray['Incompetent Material']='_3d_structures_incompetent_material_fold';
$cvarray['Label; Hint: If a label is not specified a default label will be given.']='_3d_structures_label';
$cvarray['Competent Material']='_3d_structures_lobate_competent_material';
$cvarray['Incompetent Material']='_3d_structures_lobate_incompetent_material';
$cvarray['Movement']='_3d_structures_movement';
$cvarray['Competent Material']='_3d_structures_mullion_competent_material';
$cvarray['Dip']='_3d_structures_mullion_dip';
$cvarray['Dip Direction']='_3d_structures_mullion_dip_direction';
$cvarray['Mullion Geometry']='_3d_structures_mullion_geometry';
$cvarray['Incompetent Material']='_3d_structures_mullion_incompetent_material';
$cvarray['Mullion Layer Thickness (m)']='_3d_structures_mullion_layer_thickness_m';
$cvarray['Linear Measurement Quality']='_3d_structures_mullion_linear_measure_quality';
$cvarray['Plunge']='_3d_structures_mullion_plunge';
$cvarray['Strike']='_3d_structures_mullion_strike';
$cvarray['Mullion Symmetry']='_3d_structures_mullion_symmetry';
$cvarray['Trend']='_3d_structures_mullion_trend';
$cvarray['Uncertainty']='_3d_structures_mullion_uncertainty';
$cvarray['Wavelength (m)']='_3d_structures_mullion_wavelength_m';
$cvarray['Non-ellipsoidal Tensor Notes']='_3d_structures_non_ellipsoidal_tensor_notes';
$cvarray['Non-ellipsoidal Type']='_3d_structures_non_ellipsoidal_type';
$cvarray['Orientation Uncertainty']='_3d_structures_nonellipsoidal_int_orient_unce';
$cvarray['Plunge']='_3d_structures_nonellipsoidal_int_plunge';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_int_plunge_unce';
$cvarray['Trend']='_3d_structures_nonellipsoidal_int_trend';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_int_uncertainty';
$cvarray['Value']='_3d_structures_nonellipsoidal_int_value';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_int_value_uncer';
$cvarray['Orientation Uncertainty']='_3d_structures_nonellipsoidal_max_orient_Unce';
$cvarray['Plunge']='_3d_structures_nonellipsoidal_max_plunge';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_max_plunge_unce';
$cvarray['Trend']='_3d_structures_nonellipsoidal_max_trend';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_max_trend_uncer';
$cvarray['Value']='_3d_structures_nonellipsoidal_max_value';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_max_value_uncer';
$cvarray['Orientation Uncertainty']='_3d_structures_nonellipsoidal_min_orient_Unce';
$cvarray['Plunge']='_3d_structures_nonellipsoidal_min_plunge';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_min_plunge_unce';
$cvarray['Trend']='_3d_structures_nonellipsoidal_min_trend';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_min_trend_uncer';
$cvarray['Value']='_3d_structures_nonellipsoidal_min_value';
$cvarray['Uncertainty']='_3d_structures_nonellipsoidal_min_value_uncer';
$cvarray['Quality of Measurement']='_3d_structures_nonellipsoidal_quality_of_meas';
$cvarray['Number of Necks Measured']='_3d_structures_number_of_necks_measured';
$cvarray['Other Fold Type']='_3d_structures_other_dominant_fold_geometry';
$cvarray['Other Ellipse Type']='_3d_structures_other_ellipse_type';
$cvarray['Other Ellipsoid Type']='_3d_structures_other_ellipsoid_type';
$cvarray['Other Fabric Description']='_3d_structures_other_fabric_description';
$cvarray['Other Non-ellipsoidal Type']='_3d_structures_other_non_ellipsoidal_type';
$cvarray['Other Structure Description']='_3d_structures_other_structure_description';
$cvarray['Soft Sediment Deformation Description']='_3d_structures_soft_sediment_def_description';
$cvarray['Fabric Notes']='_3d_structures_struct_notes';
$cvarray['Tectonite Character']='_3d_structures_tectonite_character';
$cvarray['Tectonite Type']='_3d_structures_tectonite_type';
$cvarray['Tightness / Interlimb Angle']='_3d_structures_tightness';
$cvarray['Type']='_3d_structures_type';
$cvarray['Vergence']='_3d_structures_vergence';
$cvarray['Wavelength (m)']='_3d_structures_wavelength_m';
$cvvals->_3d_structures = $cvarray;

unset($cvarray);
$cvarray=array();

$cvarray['Inferences:']='selectgroup';
$cvarray['Description Of Outcrop']='inferences_description_of_outcrop';
$cvarray['Notes']='inferences_notes';
$cvarray['Outcrop In Place']='inferences_outcrop_in_place';
$cvarray['Related Rosetta Outcrop']='inferences_related_rosetta_outcrop';
$cvarray['Rosetta Outcrop']='inferences_rosetta_outcrop';
$cvvals->inferences = $cvarray;

unset($cvarray);
$cvarray=array();

$cvarray['Orientation Data:']='selectgroup';
$cvarray['Alteration Zone Type']='orientation_data_alteration_zone';
$cvarray['Bedding Type; Hint: Bedding defined by? change in lithology or sedimentary feature']='orientation_data_bedding_type';
$cvarray['Contact Type; Hint: Specific contacts types under depositional, igneous and metamorphic']='orientation_data_contact_type';
$cvarray['Damage Zone Type']='orientation_data_damage_zone';
$cvarray['Damage Zone defined by']='orientation_data_damage_zone_defined_by';
$cvarray['Lineation Defined by']='orientation_data_defined_by';
$cvarray['Dip']='orientation_data_dip';
$cvarray['Dip Direction']='orientation_data_dip_direction';
$cvarray['Directional Indicators']='orientation_data_dir_indicators';
$cvarray['Directional Indicators; Hint: Specific sense of shear indicator, such as Riedel shears, S-C fabrics, drag folds, etc.']='orientation_data_directional_indicators';
$cvarray['Enveloping Surface Features']='orientation_data_enveloping_surface';
$cvarray['Enveloping Surface Features Geometry']='orientation_data_enveloping_surface_geometry';
$cvarray['Plane Facing; Hint: Orientation of plane relative to original position e.g., upright, overturned, vertical']='orientation_data_facing';
$cvarray['Plane Facing Defined By; Hint: Criteria for facing direction: e.g., stratigraphy, facing iindicators, other']='orientation_data_facing_defined_by';
$cvarray['Fault Zone or Shear Zone Type']='orientation_data_fault_or_sz';
$cvarray['Type of Fault or Shear Zone Boundary; Hint: Specific type: e.g., dextral, sinistral, normal, reverse, oblique']='orientation_data_fault_or_sz_type';
$cvarray['Linear Feature Type; Hint: Specific lineation type: e.g., striation, groove mark, intersection, fold hinge, alignment, many others']='orientation_data_feature_type';
$cvarray['Foliation Defined by']='orientation_data_foliation_defined_by';
$cvarray['Foliation Type; Hint: Specific type of foliation defined by planar and/or linear elements']='orientation_data_foliation_type';
$cvarray['Fracture Defined by']='orientation_data_fracture_defined_by';
$cvarray['Fracture Type; Hint: Specific type of fracture: e.g., joint, shear or others']='orientation_data_fracture_type';
$cvarray['Fracture Zone Type']='orientation_data_fracture_zone';
$cvarray['Fracture Zone Boundary Define By']='orientation_data_fracture_zone_def_by';
$cvarray['Geologic Age of Structure']='orientation_data_geo_age';
$cvarray['Injection Structure Type']='orientation_data_injection_type';
$cvarray['Intrusive Body Type']='orientation_data_intrusive_body_type';
$cvarray['Label; Hint: If a label is not specified a default label will be given.']='orientation_data_label';
$cvarray['Planar Feature Length (m)']='orientation_data_length';
$cvarray['Maximum Age of Structure (Ma)']='orientation_data_max_age';
$cvarray['Justification of Maximum Age']='orientation_data_max_age_just';
$cvarray['Minimum Age of Structure (Ma)']='orientation_data_min_age';
$cvarray['Justification of Minimum Age']='orientation_data_min_age_just';
$cvarray['Movement; Hint: Relative movement across structure']='orientation_data_movement';
$cvarray['Movement Amount (m); Hint: How much movement?']='orientation_data_movement_amount_m';
$cvarray['Movement Amount Qualifier']='orientation_data_movement_amount_qualifier';
$cvarray['Movement Justification; Hint: Offset feature types used to determine relative movement']='orientation_data_movement_justification';
$cvarray['Line Notes']='orientation_data_notes';
$cvarray['Other Contact Type']='orientation_data_other_contact_type';
$cvarray['Other Depositional Contact Type']='orientation_data_other_dep_contact_type';
$cvarray['Other Directional Indicator']='orientation_data_other_dir_indicators';
$cvarray['Other Directional Indicator']='orientation_data_other_directional_indic';
$cvarray['Other Plane Facing Defined By']='orientation_data_other_facing_defined_by';
$cvarray['Other Fault Zone or Shear Zone Type']='orientation_data_other_fault_or_sz';
$cvarray['Other Fault or Shear Zone Boundary Type']='orientation_data_other_fault_or_sz_type';
$cvarray['Other Linear Feature']='orientation_data_other_feature';
$cvarray['Other Foliation Type']='orientation_data_other_foliation_type';
$cvarray['Other Fracture Type']='orientation_data_other_fracture_type';
$cvarray['Other Igneous Contact Type']='orientation_data_other_ig_contact_type';
$cvarray['Other Intrusive Body']='orientation_data_other_intrusive_body';
$cvarray['Other Metamorphic Contact Type']='orientation_data_other_met_contact_type';
$cvarray['Other Movement']='orientation_data_other_movement';
$cvarray['Other Movement Justification']='orientation_data_other_movement_justification';
$cvarray['Other Surface Geometry Type']='orientation_data_other_surface_geometry';
$cvarray['Other Vein Array']='orientation_data_other_vein_array';
$cvarray['Other Vein Mineral']='orientation_data_other_vein_fill';
$cvarray['Plunge']='orientation_data_plunge';
$cvarray['Linear Measurement Quality; Hint: Quality of linear feature or of measurement']='orientation_data_quality';
$cvarray['Rake; Hint: down dip angle from strike on plane (0-180)?']='orientation_data_rake';
$cvarray['Rake Calculated?']='orientation_data_rake_calculated';
$cvarray['Stratigraphic Type']='orientation_data_strat_type';
$cvarray['Strike; Hint: Azimuth in degrees']='orientation_data_strike';
$cvarray['Tabular Thickness Type/Tabularity']='orientation_data_tabularity';
$cvarray['Planar Feature Thickness (m)']='orientation_data_thickness';
$cvarray['Trend; Hint: Azimuth in degrees']='orientation_data_trend';
$cvarray['Type']='orientation_data_type';
$cvarray['Vein Array']='orientation_data_vein_array';
$cvarray['Vein Mineral Fill; Hint: Mineral filling veins: calcite, quartz or other']='orientation_data_vein_fill';
$cvarray['Vein Type; Hint: Specific type: e.g., antitaxial, syntaxial, normal, oblique']='orientation_data_vein_type';
$cvarray['Vorticity Type; Hint: Clockwise or counterclockwise looking down plunge']='orientation_data_vorticity';
$cvvals->orientation_data = $cvarray;

unset($cvarray);
$cvarray=array();

$cvarray['Samples:']='selectgroup';
$cvarray['Degree of Weathering']='samples_degree_of_weathering';
$cvarray['Inplaceness of Sample']='samples_inplaceness_of_sample';
$cvarray['Label; Hint: If a label is not specified a default label will be given.']='samples_label';
$cvarray['Main Sampling Purpose']='samples_main_sampling_purpose';
$cvarray['Material Type']='samples_material_type';
$cvarray['Oriented Sample']='samples_oriented_sample';
$cvarray['Other Material Type']='samples_other_material_type';
$cvarray['Other Sampling Purpose']='samples_other_sampling_purpose';
$cvarray['Sample Description']='samples_sample_description';
$cvarray['Sample Specific ID/Name']='samples_sample_id_name';
$cvarray['Sample Notes']='samples_sample_notes';
$cvarray['Sample Orientation Notes']='samples_sample_orientation_notes';
$cvarray['Sample Size']='samples_sample_size';
$cvvals->samples = $cvarray;

unset($cvarray);
$cvarray=array();

$cvarray['Trace:']='selectgroup';
$cvarray['Antropogenic Feature']='trace_antropogenic_feature';
$cvarray['Contact Type']='trace_contact_type';
$cvarray['Depositional Contact Type']='trace_depositional_contact_type';
$cvarray['Fold Attitude']='trace_fold_attitude';
$cvarray['Fold Type; Hint: What is the shape of the fold when looking down-plunge?']='trace_fold_type';
$cvarray['Geologic Structure Type']='trace_geologic_structure_type';
$cvarray['Geomorphic Feature']='trace_geomorphic_feature';
$cvarray['Intrusive Contact Type']='trace_intrusive_contact_type';
$cvarray['Marker Layer Details']='trace_marker_layer_details';
$cvarray['Metamorphic Contact Type']='trace_metamorphic_contact_type';
$cvarray['Other Anthropogenic Feature']='trace_other_anthropogenic_feature';
$cvarray['Other Contact Type']='trace_other_contact_type';
$cvarray['Other Depositional Contact']='trace_other_depositional_type';
$cvarray['Other Feature']='trace_other_feature';
$cvarray['Other Fold Attitude']='trace_other_fold_attitude';
$cvarray['Other Fold Type']='trace_other_fold_type';
$cvarray['Other Geomorphic Feature']='trace_other_geomorphic_feature';
$cvarray['Other Intrusive Contact']='trace_other_intrusive_contact';
$cvarray['Other Metamorphic Contact']='trace_other_metamorphic_contact';
$cvarray['Other Other Features']='trace_other_other_feature';
$cvarray['Other Other Structural Zone']='trace_other_other_structural_zone';
$cvarray['Other Shear Sense']='trace_other_shear_sense';
$cvarray['Other Structural Zones']='trace_other_structural_zones';
$cvarray['Other Trace Character']='trace_other_trace_character';
$cvarray['Other Trace Quality']='trace_other_trace_quality';
$cvarray['Shear Sense']='trace_shear_sense';
$cvarray['Trace Character']='trace_trace_character';
$cvarray['Trace Feature']='trace_trace_feature';
$cvarray['Trace Notes']='trace_trace_notes';
$cvarray['Trace Quality']='trace_trace_quality';
$cvarray['Trace Type']='trace_trace_type';
$cvvals->trace = $cvarray;

?>