let dataFields = [
	{headerType:"Time", fieldVal:"spec_a", selectVal:"Absolute"},
	{headerType:"Time", fieldVal:"spec_a", selectVal:"Relative"},
	{headerType:"Time", fieldVal:"spec_b", selectVal:"Total"},
	{headerType:"Time", fieldVal:"spec_b", selectVal:"Differential"},
	{headerType:"Time", fieldVal:"unit", selectVal:"sec"},
	{headerType:"Time", fieldVal:"unit", selectVal:"min"},
	{headerType:"Time", fieldVal:"unit", selectVal:"hour"},
	{headerType:"Time", fieldVal:"unit", selectVal:"day"},
	{headerType:"Time", fieldVal:"unit", selectVal:"ysec"},
	{headerType:"Time", fieldVal:"unit", selectVal:"msec"},
	{headerType:"Time", fieldVal:"unit", selectVal:"%"},
	{headerType:"Time", fieldVal:"unit", selectVal:"UTC"},
	{headerType:"Time", fieldVal:"unit", selectVal:"dd-mm-yyyy"},
	{headerType:"Time", fieldVal:"unit", selectVal:"mm/dd/yy"},
	{headerType:"Time", fieldVal:"unit", selectVal:"hh-mm-ss"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Room"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Sample"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Furnace"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Fluid"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Pore"},
	{headerType:"Temperature", fieldVal:"spec_a", selectVal:"Vessel"},
	{headerType:"Temperature", fieldVal:"spec_b", selectVal:"Top"},
	{headerType:"Temperature", fieldVal:"spec_b", selectVal:"Bottom"},
	{headerType:"Temperature", fieldVal:"spec_b", selectVal:"Internal"},
	{headerType:"Temperature", fieldVal:"spec_b", selectVal:"External"},
	{headerType:"Temperature", fieldVal:"spec_b", selectVal:"Average"},
	{headerType:"Temperature", fieldVal:"unit", selectVal:"deg C"},
	{headerType:"Temperature", fieldVal:"unit", selectVal:"deg K"},
	{headerType:"Temperature", fieldVal:"unit", selectVal:"deg F"},
	{headerType:"Pressure", fieldVal:"spec_a", selectVal:"Barometric"},
	{headerType:"Pressure", fieldVal:"spec_a", selectVal:"Confining"},
	{headerType:"Pressure", fieldVal:"spec_a", selectVal:"Pore"},
	{headerType:"Pressure", fieldVal:"spec_a", selectVal:"Effective"},
	{headerType:"Pressure", fieldVal:"spec_a", selectVal:"Differential"},
	{headerType:"Pressure", fieldVal:"spec_b", selectVal:"Vessel"},
	{headerType:"Pressure", fieldVal:"spec_b", selectVal:"Intensifier"},
	{headerType:"Pressure", fieldVal:"spec_b", selectVal:"Upstream"},
	{headerType:"Pressure", fieldVal:"spec_b", selectVal:"Downstream"},
	{headerType:"Pressure", fieldVal:"unit", selectVal:"bar"},
	{headerType:"Pressure", fieldVal:"unit", selectVal:"kPa"},
	{headerType:"Pressure", fieldVal:"unit", selectVal:"MPa"},
	{headerType:"Pressure", fieldVal:"unit", selectVal:"GPa"},
	{headerType:"Pressure", fieldVal:"unit", selectVal:"PSI"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Total"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Axial"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Radial"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Shear"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Average"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Area"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"Volumetric"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"σ1"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"σ2"},
	{headerType:"Strain", fieldVal:"spec_a", selectVal:"σ3"},
	{headerType:"Strain", fieldVal:"spec_b", selectVal:"Sample"},
	{headerType:"Strain", fieldVal:"spec_b", selectVal:"Internal"},
	{headerType:"Strain", fieldVal:"spec_b", selectVal:"External"},
	{headerType:"Strain", fieldVal:"spec_b", selectVal:"Rate"},
	{headerType:"Strain", fieldVal:"unit", selectVal:"%"},
	{headerType:"Strain", fieldVal:"unit", selectVal:"mStrain"},
	{headerType:"Strain", fieldVal:"unit", selectVal:"Strain"},
	{headerType:"Strain", fieldVal:"unit", selectVal:"1/sec"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Total"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Axial"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Radial"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Shear"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Average"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Area"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"Volumetric"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"σ1"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"σ2"},
	{headerType:"Displacement", fieldVal:"spec_a", selectVal:"σ3"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Sample"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Internal"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"External"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Rate"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Pore Pressure Intensifier"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Confining Pressure Intensifier"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Pore Volume"},
	{headerType:"Displacement", fieldVal:"spec_b", selectVal:"Confining Volume"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"%"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"μm"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"mm"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"m"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"mm/s"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"inches"},
	{headerType:"Displacement", fieldVal:"unit", selectVal:"feet"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Axial"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Radial"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Shear"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Normal"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Differential"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Average"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"σ1"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"σ2"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"σ3"},
	{headerType:"Stress", fieldVal:"spec_a", selectVal:"Confining"},
	{headerType:"Stress", fieldVal:"spec_b", selectVal:"Sample"},
	{headerType:"Stress", fieldVal:"spec_b", selectVal:"Internal"},
	{headerType:"Stress", fieldVal:"spec_b", selectVal:"External"},
	{headerType:"Stress", fieldVal:"unit", selectVal:"Pa"},
	{headerType:"Stress", fieldVal:"unit", selectVal:"KPa"},
	{headerType:"Stress", fieldVal:"unit", selectVal:"MPa"},
	{headerType:"Stress", fieldVal:"unit", selectVal:"GPa"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Axial"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Radial"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Shear"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Normal"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Differential"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Average"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"σ1"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"σ2"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"σ3"},
	{headerType:"Load", fieldVal:"spec_a", selectVal:"Confining"},
	{headerType:"Load", fieldVal:"spec_b", selectVal:"Sample"},
	{headerType:"Load", fieldVal:"spec_b", selectVal:"Internal"},
	{headerType:"Load", fieldVal:"spec_b", selectVal:"External"},
	{headerType:"Load", fieldVal:"unit", selectVal:"N"},
	{headerType:"Load", fieldVal:"unit", selectVal:"KN"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Conductivity"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Resistivity"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Capacity"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Spontaneous Potential"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"AC Voltage"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"DC Voltage"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Current"},
	{headerType:"Electrical", fieldVal:"spec_a", selectVal:"Induction"},
	{headerType:"Electrical", fieldVal:"spec_b", selectVal:"Sample"},
	{headerType:"Electrical", fieldVal:"spec_b", selectVal:"Pore Fluid"},
	{headerType:"Electrical", fieldVal:"spec_b", selectVal:"Total"},
	{headerType:"Electrical", fieldVal:"spec_b", selectVal:"Heating"},
	{headerType:"Electrical", fieldVal:"spec_b", selectVal:"Cooling"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"μVolt"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"mVolt"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"Volt"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"A"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"mA"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"S"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"S/m"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"F"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"Ω"},
	{headerType:"Electrical", fieldVal:"unit", selectVal:"Ωm"},
	{headerType:"Chemistry", fieldVal:"spec_a", selectVal:"Pore Fluid"},
	{headerType:"Chemistry", fieldVal:"spec_a", selectVal:"Fluid"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"pH"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"pOH"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"Na+"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"K+"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"Ca++"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"Mg++"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"Sr++"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"HCO3-"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"TOC"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"TIC"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"CO2(gas)"},
	{headerType:"Chemistry", fieldVal:"spec_b", selectVal:"CO2(sol)"},
	{headerType:"Chemistry", fieldVal:"unit", selectVal:"mol/L"},
	{headerType:"Chemistry", fieldVal:"unit", selectVal:"mMol/L"},
	{headerType:"Chemistry", fieldVal:"unit", selectVal:"ppm"},
	{headerType:"Chemistry", fieldVal:"unit", selectVal:"cc"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Acoustic Emissions"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Acoustic Velocity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Amplitude"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Anisotropy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Area"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Attenuation"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Bulk Modulus"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Capacitance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Centrifugal Force"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Chemical Potential"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Coldness"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Concentration"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Confining Pressure"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Current Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Downstream Pore Pressure"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Dynamic Viscosity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Elasticity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Elastic Wave Velocity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electric charge"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electric Charge Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electrical Conductivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electric Current"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electrical Resistance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Electrical Resistivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Energy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Entropy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Force"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Fracture Toughness"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Frequency"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Friction Coefficient"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Heat"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Heat Capacity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Hydraulic Conductivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Impedance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Impulse"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Inductance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Intensity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Irradiance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Lame Parameter"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Length"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Linear Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Luminance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Magnetic Field Strength"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Magnetic Flux"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Mass"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Mass Concentration"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Mass Fraction"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Molar Concentration"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Molar Energy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Molar Entropy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Molar Heat Capacity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Moment of Force"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Moment of Inertia"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Momentum"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Magnetic Permittivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Permeability"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Plane Angle"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Poisson's Ratio"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Pore Pressure"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"P-Wave Modulus"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Radiance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Radioactive Dose"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Reaction Rate"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Refractive Index"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Roughness"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Shear Modulus"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Solid Angle"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Specific Energy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Specific Entropy"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Specific Heat Capacity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Specific Volume"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Spontaneous Potential"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Strain"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Streaming Potential"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Strength"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Stress"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Surface Charge Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Surface Density"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Surface Tension"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Temperature"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Temperature Gradient"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Thermal Conductance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Thermal Conductivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Thermal Resistance"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Thermal Resistivity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Time"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Torque"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Upstream Pore Pressure"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Velocity"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Volume"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Volumetric Flow Rate"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Wavelength"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Wavenumber"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Wavevector"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Weight"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Work"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Yield Strength"},
	{headerType:"Other", fieldVal:"spec_a", selectVal:"Young's Modulus"},
	{headerType:"", fieldVal:"", selectVal:""}
];